### PR TITLE
Let bots process Events concurrently

### PR DESCRIPTION
**Pull request by joehillen**
Yes, it really is this easy. :heart: Haskell :heart:

### CODE REVIEW

**Comment by mpickering** [comment]
This changes the behavior quite significantly if I understand correctly. Before, the state persisted across the whole connection but now the state is localised to the processing of each event, not as useful! Is this concurrency actually necessary? Can you not spawn threads yourself if one of your handlers needs it?

**Comment by mpickering** [comment]
Saying that, I don't know why I forced the state to be there in the first place. I think the intention was to eventually make sure that the state was updated by events (such as user's leaving/joining).

**Comment by joehillen** [comment]
Ah, I wasn't thinking about `State` in that way. I assumed you were just using `State` to pass the connection to the `SlackBot` for `sendMessage`. I was only thinking about my own use case, [ultron](https://github.com/joehillen/ultron).

I feel like a `SlackBot` should be able to manage its own `State` if it needs to. Maybe slack-api could work more like warp: https://github.com/yesodweb/yesod-cookbook/blob/master/cookbook/Keeping-%28in-memory%29-state-with-warp.md

Maybe the type for `SlackBot` could be something like `SlackBot :: Event -> (ChannelId -> Message -> IO ()) -> IO ()` where the second argument is a `sendMessage` created for each `Event`.

I'll do some tinkering and report back. It will probably require some big changes if you're open to that.

**Comment by mpickering** [comment]
Yes, tinker as you wish. I will add you as a collaborator as well.

**Comment by mpickering** [comment]
However, it doesn't seem like you answered my question.

> Is this concurrency actually necessary? Can you not spawn threads yourself if one of your handlers needs it?

**Comment by joehillen** [comment]
I tried that at first, but I forget why that didn't work.

**Comment by joehillen** [comment]
I remember now. It was because I couldn't call `sendMessage` from inside the `forkIO`.

I now realize that I could by wrapping it in `runStateT`, but that would have the same problems as this PR.

I'm closing this for now.

**Comment by mpickering** [comment]
Yes, the problem being that whenever you use `sendMessage` you need to send a unique id so that the server doesn't get confused. 

> Every event should have a unique (for that connection) positive integer ID. All replies to that message will include this ID allowing the client to correlate responses with the messages sent; replies may be "out of order" due to the asynchronous nature of the message servers.

**Pull request closed without merging**
