### PR TITLE
Made WebSocket URI parsing robust.

### PR DESCRIPTION
**Pull request by fmap**

### CODE REVIEW

**Comment by mpickering** [comment]
Is this because the URL scheme has changed? There needs to be something more robust here anyway.

**Comment by fmap** [comment]
[Documentation](https://api.slack.com/methods/rtm.start) provides as reference `wss://ms9.slack-msgs.com/websocket/7I5yBpcvk`, which is the format that I've seen; whether the URL scheme has changed, or we're on different sides of a load balancer, I don't know. `network-uri:parseURI` is bound to be more robust, I'll compose a patch for it once I'm awake.

**Comment by fmap** [comment]
Patched! :sparkle:

**Comment by mpickering** [comment]
Thanks, If you run into any more problems with the design please let me know and I'll patch them. The API is quite poorly documented but I tried to reverse engineer as much as possible.

**Pull request merged**
