### PR TITLE
Add Travis CI Integration

### PR DESCRIPTION
**Pull request by isomarcte**
Disable tests for now, as the only test we have requires an API token. We'll need to sort that out in the near future, but for now just verifying compilation is a big gain.

* GHC 8.2.1 is excluded due to the following panic. Though not include for other reasons as well, GHC 7.2.1 has the same issue too.
```
ghc: panic! (the 'impossible' happened)

  (GHC version 8.2.1 for x86_64-unknown-linux):

	getUnboxedSumName
```
* All GHC versions < 8.0.1 excluded due to a few different dependency issues. These are likely resolvable with some conditional compilation rules and/or changes to dependency constraints, but this commit just aims to get the project building with CI _as is_.

### CODE REVIEW

**Comment by isomarcte** [comment]
Please hold off on merging for a bit. I want to make sure everything builds correctly (currently happening on my fork) before we merge.

**Comment by mitchellwrosen** [comment]
Excellent work, ping me when it's ready. Then I'll merge your other open PRs.

**Comment by mitchellwrosen** [comment]
@mpickering Could you give @isomarcte commit bits if you get a chance?

**Comment by isomarcte** [comment]
@mitchellwrosen this should be ready now. I've updated the commit and PR descriptions with some information about which GHC versions were chosen.

**Comment by isomarcte** [comment]
@mitchellwrosen I'm going to rebase my current PRs on this after it is merged. I'll hold off on any new ones until then too.

**Comment by isomarcte** [comment]
FYI: https://travis-ci.org/isomarcte/slack-api/builds/573791213

**Comment by mitchellwrosen** [comment]
Awesome, great work. The only suggestion I have is I think we should be nice to TravisCI and only build on the latest point-releast of each compiler. That'd be:

- 8.0.2
- 8.2.2
- 8.4.4
- 8.6.5

**Comment by isomarcte** [comment]
@mitchellwrosen Updated.

**Comment by mitchellwrosen** [comment]
Nice. But why `8.6.4`? Is there no `8.6.5` available on ubuntu? (Will merge regardless, just curious)

**Comment by isomarcte** [comment]
@mitchellwrosen the version of `haskell-ci` I have installed locally gave an error about `8.6.5` being unknown, but I think I actually may have just built it off an older version of stackage...

Let me check.

**Comment by isomarcte** [comment]
The `haskell-ci` still reports that GHC 8.6.5 is unknown, but manually adding it to the `.travis.yml` works fine. Perhaps they haven't done a release with 8.6.5 that has made its way into Stackage yet.

In any case, it should be good now.

**Pull request merged**
