### PR TITLE
Use aeson-coerce

### LINKED ISSUE #63: Slacks stringly typed JSON
As noted in other tickets, the slack API seems to send malformed (or mixed typed?) JSON. I've another hack lying around that hooks into the `eitherDecode` function and does some type coercion on the JSON tree prior to actually parsing it.

Similarly to the other issue (#62) I just opened, I'd polish that a little and send a PR, if there's interest. This also allows to fix issues like #6, in the absence of administrator privileges (e.g. when the fix @tonyd256 provided, is not possible).

### PR DESCRIPTION
**Pull request by angerman**
This allows to fix the malformed slack json selectively.

Fixes #63

### CODE REVIEW

**Comment by mpickering** [comment]
Thanks!

**Comment by mpickering** [comment]
I have reverted this patch as it caused the test to fail.

**Comment by angerman** [comment]
I'll look into this.

**Comment by angerman** [comment]
@mpickering do you have any test errors for me?

**Comment by angerman** [comment]
Guess this is #66?

**Pull request merged**
